name: CI/CD - Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'herehave_frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar a imagem Docker
        uses: docker/build-and-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: gabrieldefende/herehave-frontend:latest # <-- NOME AJUSTADO